### ISSUE TITLE
Setting any [mixer] config param after start results in crash

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1755]
E.g. trying to set `prebuffer = 5` will result in this, or any other config param from the `[mixer]` section.

Couldn't set up `gdb` with macOS yet to get usable stacktraces as it involves generating certificates and stuff... thanks Apple!

```
2022-06-27 17:39:19.211 | MIXER: Negotiated 2-channel 48000-Hz audio in 512-frame blocks
Assertion failed: (static_cast<next_int_t<check_t>>(in) >= static_cast<next_int_t<cast_t>>(std::numeric_limits<cast_t>::min())), function check_cast, file support.h, line 206.

Loguru caught a signal: SIGABRT
2022-06-27 17:39:19.214 | Signal: SIGABRT
zsh: abort      ~/dev/jn/dosbox-staging/build/dosbox
```

**Comment by kcgen** [comment]
Nice find!

![2022-06-27_01-55](https://user-images.githubusercontent.com/1557255/175900630-fd67900a-23a6-45a2-b188-a50ffa89ae62.png)

Plain text paste:

``` text
#7  0x0000555555620c22 in check_cast<unsigned short, int> (in=-1792) at ../../include/support.h:222
No locals.
#8  0x00005555559a1d7e in MIXER_MixData (frames_requested=-767) at ../../src/hardware/mixer.cpp:1060
        capture_buf_len = 1024
        added = 23843
        pos = 21914
#9  0x000055555599f973 in MIXER_Mix () at ../../src/hardware/mixer.cpp:1106
No locals.
#10 0x00005555559d0c6d in TIMER_AddTick () at ../../src/hardware/pic.cpp:609
        nextticker = 0x55555f8302b0
        entry = 0x0
        ticker = 0x55555f7c3ab0
#11 0x000055555559599f in Normal_Loop () at ../../src/dosbox.cpp:165
        ret = 0
#12 0x00005555555959f3 in DOSBOX_RunMachine () at ../../src/dosbox.cpp:312
No locals.
#13 0x00005555556b0b34 in CALLBACK_RunRealInt (intnum=22 '\026') at ../../src/cpu/callback.cpp:106
        oldeip = 5696
        oldcs = 61440
#14 0x000055555577093a in device_CON::Read (this=0x55555f8040c0, data=0x7fffffffbdc7 "\r\376\017", size=0x7fffffffb9de) at ../../src/dos/dev_con.h:75
        oldax = 19200
        count = 0
#15 0x00005555557727d5 in DOS_Device::Read (this=0x55555f8c63e0, data=0x7fffffffbdc7 "\r\376\017", size=0x7fffffffb9de) at ../../src/dos/dos_devices.cpp:290
No locals.
#16 0x00005555557771ba in DOS_ReadFile (entry=0, data=0x7fffffffbdc7 "\r\376\017", amount=0x7fffffffbdc4, fcb=false) at ../../src/dos/dos_files.cpp:396
        handle = 1
        toread = 1
        ret = 127
#17 0x0000555555b23536 in DOS_Shell::InputCommand (this=0x55555f8d3500, line=0x7fffffffbfa0 "") at ../../src/shell/shell_misc.cpp:78
        size = 4094
        c = 13 '\r'
        n = 1
        str_len = 0
        str_index = 0
        len = 0
        current_hist = false
```

**Comment by johnnovak** [comment]
Thanks for that @kcgen
