### ISSUE TITLE
Assert failure when launching debug build fullscreen

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#3314]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82-alpha

### What Operating System are you using?

Linux x86

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

An assert failure occurs when launching a debug build fullscreen on Linux.

- Doesn't occur on macOS.
- Haven't tested Windows.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Perform a debug build on Linux: `meson --buildtype=debug build`
2. launch with: `dosbox --fullscreen`

### Provide a Log

```text
2024-01-09 20:35:13.177 | CONFIG: Loaded auto-mounted drive config file '/usr/src/dosbox-staging/build/resources/drives/y.conf'
2024-01-09 20:35:13.618 | MAPPER: Found one joystick
2024-01-09 20:35:13.619 | MAPPER: Initialised Logitech Gamepad F310 with 6 axes, 11 buttons, and 1 hat(s)
2024-01-09 20:35:13.621 | MAPPER: Loaded default key bindings
dosbox: ../include/fraction.h:43: constexpr Fraction::Fraction(int64_t, int64_t): Assertion `d != 0' failed.

Thread 1 "dosbox" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff763c3b6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff762287c in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff762279b in __assert_fail_base (fmt=0x7ffff77b9f68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555562c6e95 "d != 0", file=file@entry=0x5555562c6e7f "../include/fraction.h", line=line@entry=43, 
    function=function@entry=0x5555562c6e50 "constexpr Fraction::Fraction(int64_t, int64_t)") at ./assert/assert.c:92
#6  0x00007ffff7633b66 in __assert_fail (assertion=0x5555562c6e95 "d != 0", file=0x5555562c6e7f "../include/fraction.h", line=43, function=0x5555562c6e50 "constexpr Fraction::Fraction(int64_t, int64_t)") at ./assert/assert.c:101
#7  0x0000555555d18f6e in Fraction::Fraction (this=0x7fffffffacf0, n=1, d=0) at ../include/fraction.h:43
#8  0x0000555555d190b1 in Fraction::Inverse (this=0x5555583e32b0 <sdl+80>) at ../include/fraction.h:75
#9  0x0000555555fc256d in log_display_properties (render_width_px=640, render_height_px=480, video_mode=..., rendering_backend=RenderingBackend::OpenGl) at ../src/gui/sdlmain.cpp:797
#10 0x0000555555fcbf64 in GFX_Events () at ../src/gui/sdlmain.cpp:3847
#11 0x0000555555be7b95 in Normal_Loop () at ../src/dosbox.cpp:157
#12 0x0000555555be8256 in DOSBOX_RunMachine () at ../src/dosbox.cpp:322
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
(Screenshot of backtrace)
![2024-01-09_20-52](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/1248101d-3d49-4187-9411-1f7a81bc4449)

**Comment by johnnovak** [comment]
Init order hell. Cheers 🍻 😎
