### ISSUE TITLE
Crash when quitting while in fullscreen

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3544]
1. Start with `-noprimaryconf`
2. Alt+Enter
3. Quit

Happens on macOS 100% of the time.

<img width="980" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/015ca871-262f-4340-a92d-66de6af48648">

**Comment by shermp** [comment]
FWIW, I couldn't trigger this on Windows, using a freshly compiled `main`.

**Comment by johnnovak** [comment]
> FWIW, I couldn't trigger this on Windows, using a freshly compiled `main`.

That's good, cheers. Our init & shutdown order is platform dependent, which is terrible...

**Comment by weirddan455** [comment]
It triggers on my Linux system reliably as well.  Null pointer de-reference.

```
/usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:462: pointer std::unique_ptr<Config>::operator->() const [_Tp = Config, _Dp = std::default_delete<Config>]: Assertion 'get() != pointer()' failed.

Thread 1 "dosbox" received signal SIGABRT, Aborted.
0x00007ffff75a9834 in __pthread_kill_implementation () from /lib64/libc.so.6

(gdb) bt
#0  0x00007ffff75a9834 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ffff75578ee in raise () at /lib64/libc.so.6
#2  0x00007ffff753f8ff in abort () at /lib64/libc.so.6
#3  0x00007ffff78d95b0 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () at /lib64/libstdc++.so.6
#4  0x000000000098cc32 in std::unique_ptr<Config, std::default_delete<Config> >::operator-> (this=0x12edc60 <control>)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:462
#5  0x0000000000ea722a in setup_line_drawing_delays (total_lines=400) at ../../src/hardware/vga_draw.cpp:1455
#6  0x0000000000ea4d67 in setup_drawing () at ../../src/hardware/vga_draw.cpp:2838
#7  0x0000000000ea7658 in VGA_SetupDrawing () at ../../src/hardware/vga_draw.cpp:2928
#8  0x0000000000d3e598 in GFX_ResetScreen () at ../../src/gui/sdlmain.cpp:605
#9  0x0000000000d41b06 in GFX_SwitchFullScreen () at ../../src/gui/sdlmain.cpp:2297
#10 0x0000000000d4f9ab in GUI_ShutDown () at ../../src/gui/sdlmain.cpp:2693
#11 0x00000000009adf38 in Section::ExecuteDestroy (this=0x37391d0, destroyall=true) at ../../src/misc/setup.cpp:1272
#12 0x00000000009add94 in Section_prop::~Section_prop (this=0x37391d0) at ../../src/misc/setup.cpp:1159
#13 0x00000000009ae039 in Section_prop::~Section_prop (this=0x37391d0) at ../../src/misc/setup.cpp:1156
#14 0x00000000009aea79 in Config::~Config (this=0x37123f0) at ../../src/misc/setup.cpp:1285
#15 0x00000000009c1d3b in std::default_delete<Config>::operator() (this=0x12edc60 <control>, __ptr=0x37123f0)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:99
#16 0x0000000000d51bdc in std::__uniq_ptr_impl<Config, std::default_delete<Config> >::reset (this=0x12edc60 <control>, __p=0x0)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:211
#17 0x0000000000d5065d in std::unique_ptr<Config, std::default_delete<Config> >::reset (this=0x12edc60 <control>, __p=0x0)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:509
#18 0x0000000000d46921 in sdl_main (argc=2, argv=0x7fffffffda68) at ../../src/gui/sdlmain.cpp:4935
#19 0x000000000097f8d2 in main (argc=2, argv=0x7fffffffda68) at ../../src/main.cpp:30
(gdb) frame 5
#5  0x0000000000ea722a in setup_line_drawing_delays (total_lines=400) at ../../src/hardware/vga_draw.cpp:1455
1455            const auto conf    = control->GetSection("dosbox");
(gdb) p control
$1 = std::unique_ptr<Config> = {get() = 0x0}
```
